import { defineConfig } from "astro/config";
import react from "@astrojs/react";

// Static site (SSG) — SEO/GEO-safe HTML, React only for interactive islands.
// Sitemap is generated by src/pages/sitemap.xml.ts (the @astrojs/sitemap
// integration crashes on our endpoint routes).
export default defineConfig({
  site: "https://founderfirst.one",
  integrations: [react()],
  server: { port: 5178 },
  devToolbar: { enabled: false },
});
