/**
 * Regenerates worker/src/system-prompt.ts and worker/src/bubble-js.ts from
 * their source-of-truth files, so the Worker bundle is fully self-contained.
 *
 * Run automatically by `npm run deploy` (see worker/package.json) and any
 * time you edit penny-site-system.md or rebuild the bubble.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

// 1. system-prompt.ts ← penny-site-system.md
const md = readFileSync(resolve(root, "penny-site-system.md"), "utf8");
const escaped = md.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
writeFileSync(
  resolve(root, "src/system-prompt.ts"),
  `// Auto-generated by scripts/sync-assets.mjs — do not edit by hand.
// Source: ../penny-site-system.md.

export const SYSTEM_PROMPT_BASE = \`${escaped}\`;
`
);

// 2. bubble-js.ts ← ../bubble/dist/penny-bubble.js
const js = readFileSync(resolve(root, "../bubble/dist/penny-bubble.js"), "utf8");
writeFileSync(
  resolve(root, "src/bubble-js.ts"),
  `// Auto-generated by scripts/sync-assets.mjs — do not edit by hand.
// Source: ../../bubble/dist/penny-bubble.js. Rebuild bubble first.

export const BUBBLE_JS: string = ${JSON.stringify(js)};
`
);

console.log("✓ synced system-prompt.ts + bubble-js.ts");
